figure , axis = plt.subplots(nrows=2,ncols=3,figsize=(10,6))
x1 = np.arange(0.1,5,0.2)
y1 = np.exp(x1)
axis[0,0].plot(x1,y1,color='black',linestyle='--')
axis[0,0].set_title('Exponent Function',color='black')
x2 = np.linspace(-1,1,20)
y2 = np.cos(np.pow(x2,2))
axis[0,1].plot(x2,y2,color='orange',linestyle='-.',marker='o')
axis[0,1].set_title('Complicates Cosino Function',color='orange')
x3 = np.linspace(1,5,100)
y3 = x3**3 - 4*x3**2 + 5
max_index = int(np.argmax(x3))
x3_max = x3[max_index]
y3_max = y3[max_index]
axis[0,2].plot(x3,y3,color='pink',linestyle='-')
axis[0,2].set_title('Random Function and its derivative',color='pink')
axis[0,2].set_ylabel('Function',color='pink')
axis[0,2].annotate('Derivative is zero!',xy=(x3_max,y3_max),xytext=(x3_max+0.1,y3_max+10),fontsize=5,arrowprops=dict(width=2,color='red',shrink=0.05))
axis_der = axis[0,2].twinx()
dy3 = np.gradient(y3,x3)
axis_der.plot(x3,dy3,color = 'violet')
axis_der.set_ylabel('Its derivative',color='violet')
random_numbers = np.array([15,6,3,np.nan,89,np.nan,90])
average_value = np.nanmean(random_numbers)
mask = np.isnan(random_numbers)
random_numbers[mask] = average_value
y4 = np.sqrt(random_numbers)
axis[1,0].scatter(random_numbers,y4,marker='o',color='blue')
axis[1,0].set_title('Just random points',color='blue')
x5 = np.arange(0.1,5,0.2)
y5 = np.log(x5+1)
axis[1,1].plot(x5,y5,color='brown')
axis[1,1].set_title('Logarithm function',color='brown')
new_axis = axis[1,1].twinx()
y5_new = np.pow(x5,1.5)
new_axis.plot(x5,y5_new,color='yellow')
users = ['Sarah','John','Meghan']
np.random.seed(43)
y6 = np.random.randint(1,1000,3)
axis[1,2].bar(users,y6,edgecolor='black')
plt.tight_layout()
plt.show()
