x = np.linspace(-3,3,100)
y = np.linspace(-3, 3, 100)
X,Y = np.meshgrid(x,y)
P = np.exp(-(X**2+Y**2))
dP_dx = np.gradient(P,axis=1)
dP_dy = np.gradient(P,axis=0)
Gradient_force = np.sqrt(dP_dx**2 + dP_dy**2)
figure = plt.figure(figsize=(10,6))
axis = figure.add_subplot(111,projection='3d')
surface = axis.plot_surface(X,Y,Gradient_force,cmap='magma',alpha=0.8)
axis.set_title("3D visualization of the gradient of pressure",color='#d4a373')
axis.set_zlabel("value of the gradient",color='#d4a373')
figure.colorbar(surface,shrink=0.5,aspect=10)
plt.tight_layout()
plt.show()
