figure , axis = plt.subplots(nrows=1,ncols=2,figsize=(10,6))
parts = np.random.normal(50,2,1000)
axis[0].hist(parts,bins=50,color='green',edgecolor='black')
axis[0].set_xlabel('Diameter',color='green')
axis[0].set_ylabel('Amount of spare parts',color='green')
axis[0].axvline(50,color='red',linestyle='--',lw=2)
axis[1].hist(parts,bins=50,color='violet',edgecolor='black',cumulative=True)
axis[1].set_ylabel('Amount of spare parts',color='violet')
plt.show()
